# What is Simple Linear Regression ?

1)Simple linear regression is used to estimate the relationship
between two quantitative variables.
You can use simple linear regression when you want to know:

How strong the relationship is between two variables 
(e.g. the relationship between rainfall and soil erosion).
The value of the dependent variable at a certain value of the independent
variable (e.g. the amount of soil erosion at a certain level of rainfall).

# Assumptions of simple linear regression

Assumptions of simple linear regression
Simple linear regression is a parametric test,
meaning that it makes certain assumptions about the data.
These assumptions are:

1)Homogeneity of variance (homoscedasticity):
the size of the error in our prediction doesn’t change significantly across
the values of the independent variable.

2)Independence of observations: The observations in the dataset were collected
using statistically valid sampling methods, and there are no hidden
relationships among observations.

3)Normality: The data follows a normal distribution.

Linear regression makes one additional assumption:

4)The relationship between the independent and dependent variable is linear:
the line of best fit through the data points is a straight line 
(rather than a curve or some sort of grouping factor).

# How to perform a simple linear regression

Simple linear regression formula
The formula for a simple linear regression is:

y = B0 + B1(X) + 
y is the predicted value of the dependent variable (y) for any given value of the independent variable (x).
B0 is the intercept, the predicted value of y when the x is 0.
B1 is the regression coefficient – how much we expect y to change as x increases.
x is the independent variable ( the variable we expect is influencing y).
e is the error of the estimate, or how much variation there is in our estimate of the regression coefficient.

# What is Multiple Linear Regression ?

Multiple linear regression is used to estimate the relationship between two 
or more independent variables and one dependent variable.
You can use multiple linear regression when you want to know:

1)How strong the relationship is between two or more independent variables 
and one dependent variable (e.g. how rainfall, temperature, and amount 
                            of fertilizer added affect crop growth).

2)The value of the dependent variable at a certain value of the independent 
variables (e.g. the expected yield of a crop at certain levels of rainfall,
           temperature, and fertilizer addition).

# Assumptions of multiple linear regression

Multiple linear regression makes all of the same assumptions as 
simple linear regression:
    
  Homogeneity of variance (homoscedasticity): the size of the error in our
    prediction doesn’t change significantly across the values of the 
    independent variable.
    
  Independence of observations: the observations in the dataset were collected
    using statistically valid methods, and there are no hidden relationships 
    among variables.
    
    In multiple linear regression, it is possible that some of the independent
    variables are actually correlated with one another, so it is important to
    check these before developing the regression model. If two independent 
    variables are too highly correlated (r2 > ~0.6), then only one of them 
    should be used in the regression model.
    
  Normality: The data follows a normal distribution.
  
  Linearity: the line of best fit through the data points is a straight
        line, rather than a curve or some sort of grouping factor.

# How to perform a multiple linear regression


Multiple linear regression formula
The formula for a multiple linear regression is:

y = {\beta_0} + {\beta_1{X_1}} + … + {{\beta_n{X_n}} + {\epsilon}
y = the predicted value of the dependent variable
B_0 = the y-intercept (value of y when all other parameters are set to 0)
                                      
B_1X_1 = the regression coefficient (B_1) of the first independent variable 
(X_1) (a.k.a. the effect that increasing the value of the independent variable
has on the predicted y value)
                                      
… = do the same for however many independent variables you are testing
B_nX_n = the regression coefficient of the last independent variable
\epsilon = model error (a.k.a. how much variation there is in our estimate of y)

# Business Problem - Predict the Price of Bangalore House

In [1]:
import pandas as pd

In [4]:
# Load dataset
df = pd.read_csv("bangalore house price prediction OHE-data.csv")
df

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,150.00,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,149.00,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.0,150.00,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.0,40.00,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.0,83.00,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7115,3.0,2.0,325.00,2900.0,3,11206.896552,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7116,3.0,1.0,84.83,1780.0,3,4765.730337,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7117,2.0,1.0,48.00,880.0,2,5454.545455,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
7118,2.0,1.0,55.00,1000.0,2,5500.000000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7119,2.0,1.0,78.00,1400.0,3,5571.428571,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df.head()

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,150.0,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,149.0,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.0,150.0,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.0,40.0,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.0,83.0,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.drop("price", axis=1)
y = df["price"]

print("shape of X = ", X.shape)
print("shape of y = ", y.shape)

shape of X =  (7120, 107)
shape of y =  (7120,)

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,
                                test_size=0.2,
                                train_size=None,
                                random_state=51,
                                shuffle=True,
                                stratify=None,)

print("shape of X_train = ", X_train.shape)
print("shape of X_test = ", X_test.shape)
print("shape of y_train = ", y_train.shape)
print("shape of y_test = ", y_test.shape)

shape of X_train =  (5696, 107)
shape of X_test =  (1424, 107)
shape of y_train =  (5696,)
shape of y_test =  (1424,)

# Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

# Linear Regression - ML Model Training

In [12]:
from sklearn.linear_model import LinearRegression

In [14]:
lr = LinearRegression()

lr = LinearRegression()

Init signature:
LinearRegression(
    *,
    fit_intercept=True,
    normalize='deprecated',
    copy_X=True,
    n_jobs=None,
    positive=False,
)
Docstring:     
Ordinary least squares Linear Regression.

LinearRegression fits a linear model with coefficients w = (w1, ..., wp)
to minimize the residual sum of squares between the observed targets in
the dataset, and the targets predicted by the linear approximation.

Parameters
----------
fit_intercept : bool, default=True
    Whether to calculate the intercept for this model. If set
    to False, no intercept will be used in calculations
    (i.e. data is expected to be centered).

normalize : bool, default=False
    This parameter is ignored when ``fit_intercept`` is set to False.
    If True, the regressors X will be normalized before regression by
    subtracting the mean and dividing by the l2-norm.
    If you wish to standardize, please use
    :class:`~sklearn.preprocessing.StandardScaler` before calling ``fit``
    on an estimator with ``normalize=False``.

    .. deprecated:: 1.0
       `normalize` was deprecated in version 1.0 and will be
       removed in 1.2.

copy_X : bool, default=True
    If True, X will be copied; else, it may be overwritten.

n_jobs : int, default=None
    The number of jobs to use for the computation. This will only provide
    speedup in case of sufficiently large problems, that is if firstly
    `n_targets > 1` and secondly `X` is sparse or if `positive` is set
    to `True`. ``None`` means 1 unless in a
    :obj:`joblib.parallel_backend` context. ``-1`` means using all
    processors. See :term:`Glossary <n_jobs>` for more details.

positive : bool, default=False
    When set to ``True``, forces the coefficients to be positive. This
    option is only supported for dense arrays.

    .. versionadded:: 0.24

Attributes
----------
coef_ : array of shape (n_features, ) or (n_targets, n_features)
    Estimated coefficients for the linear regression problem.
    If multiple targets are passed during the fit (y 2D), this
    is a 2D array of shape (n_targets, n_features), while if only
    one target is passed, this is a 1D array of length n_features.

rank_ : int
    Rank of matrix `X`. Only available when `X` is dense.

singular_ : array of shape (min(X, y),)
    Singular values of `X`. Only available when `X` is dense.

intercept_ : float or array of shape (n_targets,)
    Independent term in the linear model. Set to 0.0 if
    `fit_intercept = False`.

n_features_in_ : int
    Number of features seen during :term:`fit`.

    .. versionadded:: 0.24

feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.

    .. versionadded:: 1.0

See Also
--------
Ridge : Ridge regression addresses some of the
    problems of Ordinary Least Squares by imposing a penalty on the
    size of the coefficients with l2 regularization.
Lasso : The Lasso is a linear model that estimates
    sparse coefficients with l1 regularization.
ElasticNet : Elastic-Net is a linear regression
    model trained with both l1 and l2 -norm regularization of the
    coefficients.

Notes
-----
From the implementation point of view, this is just plain Ordinary
Least Squares (scipy.linalg.lstsq) or Non Negative Least Squares
(scipy.optimize.nnls) wrapped as a predictor object.

Examples
--------
>>> import numpy as np
>>> from sklearn.linear_model import LinearRegression
>>> X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
>>> # y = 1 * x_0 + 2 * x_1 + 3
>>> y = np.dot(X, np.array([1, 2])) + 3
>>> reg = LinearRegression().fit(X, y)
>>> reg.score(X, y)
1.0
>>> reg.coef_
array([1., 2.])
>>> reg.intercept_
3.0...
>>> reg.predict(np.array([[3, 5]]))
array([16.])

In [16]:
lr.fit(X_train,y_train)

LinearRegression()

In [18]:
lr.coef_

array([-5.70206143e+00, -1.25679916e+00,  8.27341833e+01, -1.44906911e+01,
        5.75662723e+01,  1.88468905e-01, -1.72593897e+00, -4.51058311e+00,
       -2.22589244e+00, -4.28978455e+00, -2.44590976e+00,  5.40246226e-01,
       -1.03633400e+00,  1.43064873e+00, -6.25029424e-02, -1.51548783e+00,
       -2.14422789e-01,  2.16244155e+00, -1.48710228e+00,  1.95250816e+00,
       -3.10761125e+00, -1.28138668e+00, -1.01367155e+00,  1.37968545e-02,
        1.10383858e+00,  1.26497611e+00, -3.52405517e+00, -1.21398741e+00,
       -5.04622019e-01,  1.46299181e+00, -5.50064233e-01, -8.46468162e-02,
        6.84882188e-01, -1.39849820e+00, -1.94761710e-02, -1.57716300e+00,
        4.20886278e-01,  8.03443207e-01,  2.99182164e+00,  3.86430413e-03,
        1.05037261e-01,  2.89115612e-01, -3.16916626e-01,  1.05625868e+00,
       -1.39649279e+00, -3.10533604e+00,  1.01764011e-01, -7.49672917e-02,
       -8.03271555e-01, -1.27061856e+00, -8.54046164e-01,  2.64566484e-01,
        9.10688839e-01, -8.23059458e-01, -9.07215234e-01,  1.22059216e+00,
        2.11418894e+00, -5.38187400e-01, -1.32164338e+00, -8.28349340e-01,
        1.28167980e+00, -1.92911295e-01,  6.65824485e-02,  3.65563139e-02,
       -1.85069853e+00,  1.49068024e+00, -9.57964753e-01, -9.36110163e-01,
       -7.45634897e-01,  7.22643165e-02, -6.79260144e-01, -1.70853833e-01,
       -1.72288643e+00, -1.15833746e+00,  5.78931788e-01,  1.37836966e+00,
       -1.14424496e+00,  3.96188294e-01, -6.08013157e-01, -2.20959218e+00,
        3.45270810e-01,  1.01747431e-03,  1.06563895e-01,  3.04728530e+00,
        2.09496392e+00, -8.13481923e-01, -4.18437282e-01,  2.30993396e+00,
        3.31858800e-02,  8.07865914e-02,  5.37064987e-02,  1.55347699e+00,
        8.13889657e-01, -1.14636462e+00,  3.41805788e-01, -8.28022037e-01,
        1.68897360e+00,  2.97657524e-01,  9.59437517e-01,  4.57297702e-01,
       -2.22729515e-01, -1.48290835e+00, -6.26342867e-01,  5.86538254e-01,
       -1.78547310e+00,  2.19020231e-01, -3.45032599e-01])

In [19]:
lr.intercept_

95.0802729985955

# Predict the Value of Home and Test

In [21]:
X_test[0, :]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06226825,
       -0.05935999, -0.05935999, -0.05935999, -0.05630391, -0.05935999,
       -0.05785186, -0.05935999, -0.05935999, -0.06083125, -0.06083125,
       -0.05471275, -0.06083125, -0.06226825, -0.05935999, -0.05935999,
       -0.06226825, -0.06226825, -0.05785186, -0.06504853, -0.06226825,
       -0.06083125, -0.05935999, -0.05307449, -0.05630391, -0.06226825,
       -0.05471275, -0.05935999, -0.05471275, -0.05471275, -0.05138463,
       -0.05307449, -0.05307449, -0.05471275, -0.05471275, -0.05630391,
       -0.05630391, -0.05138463])

In [22]:
lr.predict([X_test[0, :]])

array([76.90661876])

In [23]:
lr.predict(X_test)

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [24]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [25]:
lr.score(X_test,y_test)

0.7903837092682244